MarcStore/Controllers/AdminController.cs
using MarcStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text.RegularExpressions;
using System;

namespace MarcStore.Controllers
{

    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private IProductRepository repository;
        public const int ImageMinimumBytes = 512;

        public AdminController(IProductRepository repository)
        {
            this.repository = repository;
        }
        public ViewResult Index() => View(repository.Products);
        public ViewResult Edit(int productId) =>
            View(repository.Products.FirstOrDefault(p => p.ProductID == productId));

        public static bool IsImage(IFormFile postedFile)
        {

            //-------------------------------------------
            //  Check the image mime types
            //-------------------------------------------
            if (postedFile.ContentType.ToLower() != "image/jpg" &&
                        postedFile.ContentType.ToLower() != "image/jpeg" &&
                        postedFile.ContentType.ToLower() != "image/pjpeg" &&
                        postedFile.ContentType.ToLower() != "image/gif" &&
                        postedFile.ContentType.ToLower() != "image/x-png" &&
                        postedFile.ContentType.ToLower() != "image/png")
            {
                return false;
            }

            //-------------------------------------------
            //  Check the image extension
            //-------------------------------------------
            if (Path.GetExtension(postedFile.FileName).ToLower() != ".jpg"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".png"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".gif"
                && Path.GetExtension(postedFile.FileName).ToLower() != ".jpeg")
            {
                return false;
            }

            //-------------------------------------------
            //  Attempt to read the file and check the first bytes
            //-------------------------------------------
            try
            {
                if (!postedFile.OpenReadStream().CanRead)
                {
                    return false;
                }

                if (postedFile.Length < ImageMinimumBytes)
                {
                    return false;
                }

                byte[] buffer = new byte[512];
                postedFile.OpenReadStream().Read(buffer, 0, 512);
                string content = System.Text.Encoding.UTF8.GetString(buffer);
                if (Regex.IsMatch(content, @"<script|<html|<head|<title|<body|<pre|<table|<a\s+href|<img|<plaintext|<cross\-domain\-policy",
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Multiline))
                {
                    return false;
                }
            }
            catch (Exception)
            {
                return false;
            }
            return true;
        }
        [HttpPost]
        public IActionResult DeleteImage(int productId)
        {
            Product product = repository.Products.FirstOrDefault(i => i.ProductID == productId);
            if (product != null)
            {
                product.ImageData = null;
                product.ImageMimeType = null;
                repository.SaveProduct(product);
            }
            return View("Edit",productId);
        }
        [HttpPost]
        public IActionResult Edit(Product product, IFormFile image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    if (IsImage(image))
                    {
                        product.ImageMimeType = image.ContentType;
                        product.ImageData = new byte[image.Length];
                        image.OpenReadStream().Read(product.ImageData, 0, (int)image.Length);
                    }
                    else
                    {
                        TempData["error"] = $"It's not image";
                        return View(product);
                    }

                }
                repository.SaveProduct(product);
                TempData["message"] = $"{product.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public IActionResult Menu() => View();
        public ViewResult Create() => View("Edit", new Product());

        [HttpPost]
        public IActionResult Delete(int productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
                TempData["message"] = $"{ deletedProduct.Name} was deleted";
            else
                TempData["message"] = $"{ deletedProduct.Name} was'nt deleted";

            return RedirectToAction("Index");
        }
    }
}

MarcStore/Controllers/OrderController.cs
 using Microsoft.AspNetCore.Mvc;
using MarcStore.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
namespace MarcStore.Controllers
{
   [Authorize]
    public class OrderController:Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrderController(IOrderRepository repoService,Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult List() =>
            View(repository.Orders.Where(o => !o.Shipped));
        [HttpPost]
        public IActionResult MarkShipped(int orderID)
        {
            Order order = repository.Orders
                .FirstOrDefault(o => o.OrderID == orderID);
            if (order!=null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count()==0)
            {
                ModelState.AddModelError("", "Sorry,your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }

}

MarcStore/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using MarcStore.Models;
using MarcStore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;

namespace MarcStore.Controllers
{
    [Authorize(Roles ="admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }

}

MarcStore/Views/Admin/Edit.cshtml
@model Product

@{
    ViewBag.Title = $"Edit Product «{Model.Name}»";
    Layout = "_AdminLayout";
}

<div class="panel">
    @using (Html.BeginForm("Edit", "Admin",
FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(p => p.ProductID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "ProductID":
                    case "ImageData":
                    case "ImageMimeType":

                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description" || property.PropertyName == "Text")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">

                <div style="position:relative;">
                    <label>Image</label>
                    <a class='btn' href='javascript:;'>
                        Select File...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                        left:0;filter: alpha(opacity=0); opacity:0;
                        background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger">@TempData["error"]</div>
                }
                else
                {
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">No Image</div>
                    }
                    else
                    {

                        <img class="img-thumbnail" width="150" height="150"
                             src="@Url.Action("GetImage", "Product",
                        new { Model.ProductID })" />
                        @using (Html.BeginForm("DeleteImage", "Admin", FormMethod.Post))
                        {
                            @Html.HiddenFor(p => p.ProductID)
                            <button type="submit" class="btn btn-danger btn-sm">
                                Delete
                            </button>
                        }
                    }

                }

            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" asp-controller="Admin" class="btn btn-danger">Cancel</a>
        </div>
    }
</div>

MarcStore/Views/Admin/Index.cshtml
@model IEnumerable<Product>
@{
    ViewBag.Title = "All Products";
    Layout = "_AdminLayout";
}
<table class="table table-striped table-bordered table-condensed">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th class="text-right">Price</th>
        <th class="text-center">Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.ProductID</td>
            <td>@item.Name</td>
            <td class="text-right">@item.Price.ToString("c")</td>
            <td class="text-center">
                @using (Html.BeginForm("Delete", "Admin", FormMethod.Post))
                {

                    <a asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-productID="@item.ProductID">
                        Edit
                    </a>
                    <input type="hidden" name="ProductID" value="@item.ProductID" />
                    <button type="submit" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                }
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Product</a>
</div>

MarcStore/Views/Admin/Menu.cshtml
@{
    ViewBag.Title = "Menu";
    Layout = "_AdminLayout";
}

<table class="table">
    <tr>
        <th scope="col" class="text-center">Menu For Admin</th>
    </tr>
    <tr class="text-center">
        <td scope="row"><a class="btn btn-success" asp-action="List" asp-controller="Order">Orders</a></td>
    </tr>
    <tr class="text-center">
        <td scope="row"><a class="btn btn-success" asp-action="Index">Products</a></td>
    </tr>
    <tr class="text-center">
        <td scope="row"><a class="btn btn-success" asp-action="Index" asp-controller="Users">Users</a></td>
    </tr>
    <tr class="text-center">
        <td scope="row"><a class="btn btn-success" asp-action="Index" asp-controller="Roles">Roles</a></td>
    </tr>
    <tr class="text-center">
        <td scope="row"><a class="btn btn-primary" asp-action="List" asp-controller="Product">Home</a></td>
    </tr>
</table>